### ISSUE TITLE
Add a Code of Conduct / Contributor Covenant to Alvearie

### ISSUE THREAD

**Issue by DaveMurrells** [Alvearie/alvearie.github.io#3]
I believe Alvearie should have a code of conduct and

https://www.contributor-covenant.org/

seems a sensible one.  As well as adding one to the Root of the repository of every "service" linked under the Alvearie banner it should be linked from the top level home page.  Note certain repos have a contributing file in their root and others do not.

**Comment by eggebraa** [comment]
Great suggestion.  I'll look at how to incorporate into the website and services when I return to work in 2021.

**Comment by eggebraa** [comment]
Added code of conduct to Alvearie website.
