### ISSUE TITLE
Reflect License at Alvearie home page

### ISSUE THREAD

**Issue by DaveMurrells** [Alvearie/alvearie.github.io#4]
Given Alvearie is an umbrella pipeline which contains a number of "services" as per home page I believe it is a sensible expectation that all "services" have the same Open Source license.  I believe it would be useful to say this on the home page (which doesn't negate the continued need to have a license file in the root of each repository)

**Comment by eggebraa** [comment]
I added a statement about the license on the Getting Involved page.  That may get refactored when the designers change things, but it's there for now.
